use std::fmt::{self, Write};
use std::hash::{Hash, Hasher};

use crate::themes::compiled::{CompiledTheme, CompiledThemeRule};
use crate::themes::selector::ThemeSelector;
use rustc_hash::FxHasher;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub(crate) enum Property {
    /// fg colour
    Fg,
    /// bg colour
    Bg,
    /// any font style change
    Ft,
}

impl Property {
    pub(crate) const fn as_str(self) -> &'static str {
        match self {
            Self::Fg => "fg",
            Self::Bg => "bg",
            Self::Ft => "ft",
        }
    }
}

/// A Class ID is what will be used in the CSS file and as class.
/// It looks like fg-{hash}, bg-{hash} and ft-{hash}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub(crate) struct ClassId {
    pub(crate) property: Property,
    pub(crate) hash: u64,
}

impl ClassId {
    pub(crate) fn new(selector: &ThemeSelector, property: Property) -> Self {
        let mut hasher = FxHasher::default();
        hasher.write(property.as_str().as_bytes());
        hasher.write(b"|");
        selector.hash(&mut hasher);
        Self {
            property,
            hash: hasher.finish(),
        }
    }
}

impl fmt::Display for ClassId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}-{:016x}", self.property.as_str(), self.hash)
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub(crate) struct RuleClassIds {
    pub fg: ClassId,
    pub bg: ClassId,
    pub ft: ClassId,
}

impl From<&CompiledThemeRule> for RuleClassIds {
    fn from(rule: &CompiledThemeRule) -> Self {
        Self {
            fg: ClassId::new(&rule.selector, Property::Fg),
            bg: ClassId::new(&rule.selector, Property::Bg),
            ft: ClassId::new(&rule.selector, Property::Ft),
        }
    }
}

/// Generates the CSS content for a textmate theme
///
/// This is used with the HTML renderer, typically to switch highlighting scheme in light/dark
/// mode which is something that cannot be done inline.
pub fn generate_css(theme: &CompiledTheme, prefix: &str) -> String {
    let mut css = String::new();
    debug_assert_eq!(theme.rules.len(), theme.class_ids.len());

    // Add header comment
    writeln!(css, "/*").unwrap();
    writeln!(
        css,
        " * theme \"{}\" generated by giallo {}",
        theme.name,
        env!("CARGO_PKG_VERSION")
    )
    .unwrap();
    writeln!(css, " */").unwrap();
    writeln!(css).unwrap();

    // Generate base code class with default theme colors
    writeln!(css, ".{prefix}code {{").unwrap();
    writeln!(
        css,
        "  {}",
        theme.default_style.foreground.as_css_color_property()
    )
    .unwrap();
    writeln!(
        css,
        "  {}",
        theme.default_style.background.as_css_bg_color_property()
    )
    .unwrap();
    writeln!(css, "}}").unwrap();
    writeln!(css).unwrap();

    if let Some(ref highlight_bg) = theme.highlight_background_color {
        writeln!(css, ".{prefix}hl {{").unwrap();
        writeln!(css, "  {}", highlight_bg.as_css_bg_color_property()).unwrap();
        writeln!(css, "}}").unwrap();
        writeln!(css).unwrap();
    }

    // Generate line number color class if theme has one
    if let Some(ref line_number_fg) = theme.line_number_foreground {
        writeln!(css, ".giallo-ln {{").unwrap();
        writeln!(css, "  {}", line_number_fg.as_css_color_property()).unwrap();
        writeln!(css, "}}").unwrap();
        writeln!(css).unwrap();
    }

    // Generate CSS for each theme rule
    for (rule, class_ids) in theme.rules.iter().zip(theme.class_ids.iter()) {
        if rule.style_modifier.has_properties() {
            generate_rule_css(&mut css, rule, class_ids, prefix);
        }
    }

    css
}

/// Generate CSS rules for a single theme rule.
fn generate_rule_css(
    css: &mut String,
    rule: &CompiledThemeRule,
    class_ids: &RuleClassIds,
    prefix: &str,
) {
    if let Some(fg) = rule.style_modifier.foreground {
        writeln!(
            css,
            ".{prefix}{} {{ {} }}",
            class_ids.fg,
            fg.as_css_color_property()
        )
        .unwrap();
    }

    if let Some(bg) = rule.style_modifier.background {
        writeln!(
            css,
            ".{prefix}{} {{ {} }}",
            class_ids.bg,
            bg.as_css_bg_color_property()
        )
        .unwrap();
    }

    if let Some(font_style) = rule.style_modifier.font_style {
        if font_style.is_empty() {
            // Explicit reset for `fontStyle: ""` so class mode preserves override semantics.
            writeln!(
                css,
                ".{prefix}{} {{ font-style: normal;font-weight: normal;text-decoration: none; }}",
                class_ids.ft
            )
            .unwrap();
        } else {
            let declaration = font_style.css_attributes().join("");
            writeln!(css, ".{prefix}{} {{ {declaration} }}", class_ids.ft).unwrap();
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::themes::RawTheme;
    use crate::themes::compiled::{StyleModifier, ThemeType};
    use crate::themes::selector::parse_selector;
    use crate::themes::{CompiledTheme, FontStyle, Style};
    use insta::assert_snapshot;

    fn selector_to_rule(selector: &str) -> CompiledThemeRule {
        CompiledThemeRule {
            selector: parse_selector(selector).unwrap(),
            style_modifier: StyleModifier::default(),
        }
    }

    #[test]
    fn can_generate_css_for_theme() {
        let theme = RawTheme::load_from_file(
            "grammars-themes/packages/tm-themes/themes/vitesse-black.json",
        )
        .unwrap()
        .compile()
        .unwrap();
        assert_snapshot!(generate_css(&theme, "g-"));
    }

    #[test]
    fn test_rule_property_class_id_preserves_selector_structure() {
        let selector_a = selector_to_rule("meta.selectionset.graphql meta.arguments variable");
        let selector_b = selector_to_rule(
            "meta.selectionset.graphql meta.arguments.graphql variable.arguments.graphql",
        );

        let class_a = ClassId::new(&selector_a.selector, Property::Fg);
        let class_b = ClassId::new(&selector_b.selector, Property::Fg);

        assert_ne!(class_a, class_b);
    }

    #[test]
    fn test_rule_property_class_id_preserves_combinators() {
        let anywhere = selector_to_rule("meta.arguments variable");
        let direct = selector_to_rule("meta.arguments > variable");

        let class_anywhere = ClassId::new(&anywhere.selector, Property::Fg);
        let class_direct = ClassId::new(&direct.selector, Property::Fg);

        assert_ne!(class_anywhere, class_direct);
    }

    #[test]
    fn test_rule_property_class_id_preserves_property() {
        let rule = selector_to_rule("string");
        let fg = ClassId::new(&rule.selector, Property::Fg);
        let bg = ClassId::new(&rule.selector, Property::Bg);
        let ft = ClassId::new(&rule.selector, Property::Ft);

        assert_ne!(fg, bg);
        assert_ne!(fg, ft);
        assert_ne!(bg, ft);
    }

    #[test]
    fn test_generate_css_emits_font_style_reset_for_empty_font_style() {
        let rules = vec![CompiledThemeRule {
            selector: parse_selector("string").unwrap(),
            style_modifier: StyleModifier {
                foreground: None,
                background: None,
                font_style: Some(FontStyle::default()),
            },
        }];
        let class_ids = rules.iter().map(RuleClassIds::from).collect();

        let theme = CompiledTheme {
            name: "Reset Test".to_string(),
            theme_type: ThemeType::Dark,
            default_style: Style::default(),
            highlight_background_color: None,
            line_number_foreground: None,
            rules,
            class_ids,
        };

        let css = generate_css(&theme, "g-");
        assert!(css.contains("font-style: normal;font-weight: normal;text-decoration: none;"));
    }
}
